<?php

namespace Rm\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategorie($categorie){
        $qry = $this->createQueryBuilder('a')
            ->leftJoin('a.categorie', 'c')
            ->addSelect('c')
            ->andWhere("c.slug = '".$categorie."'")
//            ->orderBy('a.publishDate', 'DESC')
            ->getQuery();

        $results = $qry->getResult();

        return $results;
    }
}
