<?php

namespace Rm\BlogBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategorie($categorie, $page, $nbParPage){
        $qry = $this->createQueryBuilder('a')
            ->leftJoin('a.categorie', 'c')
            ->addSelect('c')
            ->andWhere("c.slug = '".$categorie."'")
            ->orderBy('a.publishDate', 'DESC')
            ->getQuery();

        $qry->setFirstResult(($page-1) * $nbParPage)
            ->setMaxResults($nbParPage);

        return new Paginator($qry, true);
    }

    public function findArticles($page, $nbParPage){
        $qry = $this->createQueryBuilder('a')
            ->orderBy('a.publishDate', 'DESC')
            ->getQuery();

        $qry->setFirstResult(($page-1) * $nbParPage)
            ->setMaxResults($nbParPage);

        return new Paginator($qry, true);
    }
}
