rm_blog:
    path:     /{categorie}
    defaults:
        _controller: RmBlogBundle:Blog:index
        categorie:   all

rm_blog_article:
    path:     /article/{nom}
    defaults:
        _controller: RmBlogBundle:Blog:article